### ISSUE TITLE
关于 A4LoadMeasure 的 hookAllLoadMethods

### ISSUE THREAD

**Issue by SuperSG** [tripleCC/Laboratory#2]
有个问题 你hookAllLoadMethods 这个方法中每次都会把一个类在所有framework的分类+load都hook一次，这样最后生成的LMLoadInfoWappers是不是就会含有重复的load信息

**Comment by tripleCC** [comment]
`每次都会把一个类在所有framework的分类+load都hook一次` 不是很理解这句的意思，有例子么

hookAllLoadMethods 执行实现 +load 类 / 分类的 hook 动作时，分类的 +load 方法已经在其类的元类的方法列表里面了，这时候遍历元类的方法列表，得到 +load 方法个数，和实现 +load 方法的 类 + 分类 个数是相等的，每个 +load 方法只会替换一次 imp

**Comment by SuperSG** [comment]
比如有2个动态库A，B， UIViewcontroller分别在A，B中都有分类并且实现了+load方法，由于hookAllLoadMethods这个方法是在遍历每一个framework时候都会调用一次，其中的方法class_copyMethodList(metaCls, &class_method_count); 每次都会获取metaCls的所有方法，这个时候是不是出现在A动态库中的UIViewcontroller分类的+load方法 在B动态库中遍历UIViewcontroller的方法列表的时候也会遍历出来，这样就会导致在下面判断的时候会生成之前已经加入过的LMLoadInfo 对象

**Comment by SuperSG** [comment]
然后这里还有第二个问题，你好像考虑漏了系统的share lib实现+load的情况，比如NSObject，在core foundation， Foundation， liboject.dylib里面都有实现+load方法，在调用class_copyMethodList的时候，会遍历出这三个方法，命中后被hook，这时候你的计数器LMAllLoadNumber会算上这三个+load，但是实际上这是三个+load在你hook他们之前已经执行完了，所以 if (!--LMAllLoadNumber) printLoadInfoWappers(); 这个判断就走不到了。

**Comment by tripleCC** [comment]
嗯，发现这个问题了,看来还是需要用 load 函数地址来区分，利用load方法的顺序不可靠，多谢指出

**Comment by SuperSG** [comment]
要不要加个微信继续探索一下

**Comment by tripleCC** [comment]
我微信号同github

**Comment by zhuangtao97** [comment]
貌似问题并没有解决

**Comment by binzi56** [comment]
不清楚为啥纠结利用LMAllLoadNumber实现到最后一个方法执行完才打印, 记录已经有了, 完全可以延迟到主线程去打印.
LMAllLoadNumber单看里面的逻辑都有可能造成走不到LMAllLoadNumber==0的情况;
